apiVersion: v1
kind: Namespace
metadata:
  name: clickhouse
---
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: aiproject
  namespace: clickhouse
spec:
  configuration:
    users:
      aiproject_app/password: "7jui2G8OHO1FZb2NIEt_5av1"
      aiproject_app/networks/ip: "::/0"
      aiproject_app/profile: default
      aiproject_app/quota: default
    clusters:
      - name: default
        layout:
          shardsCount: 1
          replicasCount: 1
  defaults:
    templates:
      podTemplate: default
      dataVolumeClaimTemplate: data-storage
      logVolumeClaimTemplate: log-storage
  templates:
    podTemplates:
      - name: default
        spec:
          nodeSelector:
            kubernetes.io/hostname: tsl01.tech-sphere.pro
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:24.3
              resources:
                requests:
                  cpu: 200m
                  memory: 512Mi
                limits:
                  cpu: 1000m
                  memory: 2Gi
    volumeClaimTemplates:
      - name: data-storage
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
      - name: log-storage
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
