from __future__ import annotations

from app.config import Settings
from app.schemas import ModelRecord, Policy, PolicyRuleSet, ProviderConfig, RuntimeConfig


def load_model_registry() -> list[ModelRecord]:
    return [
        ModelRecord(
            model="gpt-4o-mini",
            provider="openai",
            mode="balanced",
            cost_per_1k_input_tokens=0.00015,
            cost_per_1k_output_tokens=0.0006,
            avg_latency_ms=850,
            quality_score=0.81,
            error_rate=0.008,
            supports_tools=True,
            supports_streaming=True,
            tags=["default", "fast", "live"],
        ),
        ModelRecord(
            model="gpt-4.1",
            provider="openai",
            mode="premium",
            cost_per_1k_input_tokens=0.002,
            cost_per_1k_output_tokens=0.008,
            avg_latency_ms=1600,
            quality_score=0.93,
            error_rate=0.006,
            supports_tools=True,
            supports_streaming=True,
            tags=["quality", "live"],
        ),
        ModelRecord(
            model="qwen3.5:4b",
            provider="ollama",
            mode="economy",
            cost_per_1k_input_tokens=0.0,
            cost_per_1k_output_tokens=0.0,
            avg_latency_ms=950,
            quality_score=0.73,
            error_rate=0.02,
            tags=["ollama", "local", "live"],
        ),
        ModelRecord(
            model="qwen3.5:latest",
            provider="ollama",
            mode="balanced",
            cost_per_1k_input_tokens=0.0,
            cost_per_1k_output_tokens=0.0,
            avg_latency_ms=1300,
            quality_score=0.82,
            error_rate=0.02,
            tags=["ollama", "local", "live"],
        ),
        ModelRecord(
            model="deepseek-r1:1.5b",
            provider="ollama",
            mode="economy",
            cost_per_1k_input_tokens=0.0,
            cost_per_1k_output_tokens=0.0,
            avg_latency_ms=700,
            quality_score=0.68,
            error_rate=0.03,
            tags=["ollama", "local", "reasoning", "live"],
        ),
        ModelRecord(
            model="deepseek-r1:8b",
            provider="ollama",
            mode="premium",
            cost_per_1k_input_tokens=0.0,
            cost_per_1k_output_tokens=0.0,
            avg_latency_ms=1800,
            quality_score=0.88,
            error_rate=0.025,
            tags=["ollama", "local", "reasoning", "live"],
        ),
        ModelRecord(
            model="gemma3:latest",
            provider="ollama",
            mode="balanced",
            cost_per_1k_input_tokens=0.0,
            cost_per_1k_output_tokens=0.0,
            avg_latency_ms=1000,
            quality_score=0.76,
            error_rate=0.02,
            tags=["ollama", "local", "live"],
        ),
        ModelRecord(
            model="qwen3:0.6b",
            provider="ollama",
            mode="economy",
            cost_per_1k_input_tokens=0.0,
            cost_per_1k_output_tokens=0.0,
            avg_latency_ms=450,
            quality_score=0.55,
            error_rate=0.03,
            tags=["ollama", "local", "live"],
        ),
        ModelRecord(
            model="qwen3:8b",
            provider="ollama",
            mode="premium",
            cost_per_1k_input_tokens=0.0,
            cost_per_1k_output_tokens=0.0,
            avg_latency_ms=1400,
            quality_score=0.84,
            error_rate=0.025,
            tags=["ollama", "local", "live"],
        ),
        ModelRecord(
            model="claude-3-5-haiku",
            provider="anthropic",
            mode="balanced",
            cost_per_1k_input_tokens=0.0008,
            cost_per_1k_output_tokens=0.004,
            avg_latency_ms=1100,
            quality_score=0.86,
            error_rate=0.009,
            supports_streaming=True,
            tags=["fallback", "not-live"],
        ),
        ModelRecord(
            model="mistral-small",
            provider="mistral",
            mode="economy",
            cost_per_1k_input_tokens=0.0002,
            cost_per_1k_output_tokens=0.0006,
            avg_latency_ms=700,
            quality_score=0.72,
            error_rate=0.012,
            supports_streaming=True,
            tags=["cheap", "not-live"],
        ),
        ModelRecord(
            model="llama-3.3-70b-versatile",
            provider="groq",
            mode="balanced",
            cost_per_1k_input_tokens=0.00059,
            cost_per_1k_output_tokens=0.00079,
            avg_latency_ms=600,
            quality_score=0.88,
            error_rate=0.01,
            supports_tools=True,
            supports_streaming=True,
            tags=["groq", "fast", "not-live"],
        ),
        ModelRecord(
            model="mistral-large-latest",
            provider="mistral",
            mode="premium",
            cost_per_1k_input_tokens=0.002,
            cost_per_1k_output_tokens=0.006,
            avg_latency_ms=1200,
            quality_score=0.90,
            error_rate=0.01,
            supports_tools=True,
            supports_streaming=True,
            tags=["mistral", "not-live"],
        ),
        ModelRecord(
            model="gemini-2.0-flash",
            provider="gemini",
            mode="balanced",
            cost_per_1k_input_tokens=0.0001,
            cost_per_1k_output_tokens=0.0004,
            avg_latency_ms=800,
            quality_score=0.87,
            error_rate=0.01,
            supports_tools=True,
            supports_streaming=True,
            tags=["gemini", "fast", "not-live"],
        ),
    ]


def load_policies() -> list[Policy]:
    return [
        Policy(
            policy_id="org-default",
            scope="org",
            scope_id="techsphere",
            rules=PolicyRuleSet(
                max_cost_per_request=0.03,
                blocked_terms=["credit card", "social security"],
                fallback_model="gpt-4o-mini",
            ),
        ),
        Policy(
            policy_id="team-platform",
            scope="team",
            scope_id="platform",
            rules=PolicyRuleSet(
                max_cost_per_request=0.015,
                allowed_models=[
                    "gpt-4o-mini",
                    "gpt-4.1",
                    "qwen3.5:4b",
                    "qwen3.5:latest",
                    "deepseek-r1:1.5b",
                    "deepseek-r1:8b",
                    "gemma3:latest",
                    "qwen3:0.6b",
                    "qwen3:8b",
                ],
                blocked_terms=["pii"],
                fallback_model="qwen3.5:latest",
            ),
        ),
    ]


def default_provider_configs(settings: Settings) -> list[ProviderConfig]:
    return [
        ProviderConfig(
            provider_id="openai",
            provider_type="openai",
            enabled=settings.openai_enabled,
            base_url=settings.openai_base_url,
            api_key=settings.openai_api_key,
            organization=settings.openai_organization,
            project=settings.openai_project,
            timeout_seconds=settings.openai_timeout_seconds,
            labels={"kind": "saas"},
        ),
        ProviderConfig(
            provider_id="ollama",
            provider_type="ollama",
            enabled=settings.ollama_enabled,
            base_url=settings.ollama_base_url,
            timeout_seconds=settings.ollama_timeout_seconds,
            labels={"kind": "local"},
        ),
        ProviderConfig(
            provider_id="anthropic",
            provider_type="anthropic",
            enabled=settings.anthropic_enabled,
            base_url=settings.anthropic_base_url,
            api_key=settings.anthropic_api_key,
            timeout_seconds=settings.anthropic_timeout_seconds,
            labels={"kind": "saas"},
        ),
        ProviderConfig(
            provider_id="kimi",
            provider_type="kimi",
            enabled=settings.kimi_enabled,
            base_url=settings.kimi_base_url,
            api_key=settings.kimi_api_key,
            timeout_seconds=settings.kimi_timeout_seconds,
            labels={"kind": "saas"},
        ),
        ProviderConfig(
            provider_id="groq",
            provider_type="groq",
            enabled=settings.groq_enabled,
            base_url=settings.groq_base_url,
            api_key=settings.groq_api_key,
            timeout_seconds=settings.groq_timeout_seconds,
            labels={"kind": "saas"},
        ),
        ProviderConfig(
            provider_id="mistral",
            provider_type="mistral",
            enabled=settings.mistral_enabled,
            base_url=settings.mistral_base_url,
            api_key=settings.mistral_api_key,
            timeout_seconds=settings.mistral_timeout_seconds,
            labels={"kind": "saas"},
        ),
        ProviderConfig(
            provider_id="gemini",
            provider_type="gemini",
            enabled=settings.gemini_enabled,
            base_url=settings.gemini_base_url,
            api_key=settings.gemini_api_key,
            timeout_seconds=settings.gemini_timeout_seconds,
            labels={"kind": "saas"},
        ),
        ProviderConfig(
            provider_id="azure-openai",
            provider_type="azure_openai",
            enabled=settings.azure_openai_enabled,
            base_url=settings.azure_openai_base_url,
            api_key=settings.azure_openai_api_key,
            timeout_seconds=settings.azure_openai_timeout_seconds,
            labels={"kind": "saas", "api_version": settings.azure_openai_api_version},
        ),
    ]


def build_default_runtime_config(settings: Settings) -> RuntimeConfig:
    return RuntimeConfig(
        providers=default_provider_configs(settings),
        models=load_model_registry(),
        policies=load_policies(),
    )
